version: "3.9"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    command: sh -c "aws --endpoint-url=http://localhost:4566 s3 mb s3://nyc-duration && 
                aws --endpoint-url=http://localhost:4566 s3 ls"
    env_file:
      - localstack.env
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./:/app"
